name=PTSolns_I2Connect_KXTJ3_1057
version=1.0.0
author=PTSolns
maintainer=PTSolns <support@ptsolns.com>
sentence=Library for the PTSolns I2Connect KXTJ3-1057 accelerometer module.
paragraph=Provides a streamlined interface to read multi-axis acceleration, detect motion, and manage low-power states for the KXTJ3-1057 accelerometer using I2C.
category=Sensors
url=https://github.com/PTSolns/I2Connect_KXTJ3-1057
architectures=*
includes=PTSolns_I2Connect_KXTJ3_1057.h
